name: Unity Build with Submodules

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Fetch Artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          repo: VRS-NDA/VRS-Unity
          name: WebGLBuild
          workflow: main.yml
          #workflow_search: false
          #workflow_conclusion: success
          #check_artifacts: true
          branch: decode
          path: ./downloaded
          github_token: ${{ secrets.ARTIFACT_DOWNLOADER_TOKEN }}
      - run: |
          mkdir -p ./imported-files
          unzip -o ./downloaded/build-artifact.zip -d ./imported-files
